/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { useFrame } from "@react-three/fiber"
import { editable as e } from "@theatre/r3f"

import { MaterialGreen, MaterialRed, MaterialWater } from "../materials"

const Miyajima = () => {
  const { nodes } = useGLTF("/planets/miyajima.gltf")

  const ref: null | { current: THREE.Mesh } = useRef()

  useFrame(() => {
    if (ref) {
      const x = ref.current.rotation.x + 0.0005
      const y = ref.current.rotation.y + 0.002
      const z = ref.current.rotation.z + 0.0005
      ref.current.rotation.set(x, y, z)
    }
  })
  return (
    <e.group dispose={null} theatreKey="Planet Miyajima">
      <group scale={15} position={[-100, 175, 40]} ref={ref}>
        <mesh geometry={nodes.water.geometry}>
          <MaterialWater />
        </mesh>
        <mesh geometry={nodes.green.geometry}>
          <MaterialGreen />
        </mesh>
        <mesh geometry={nodes.red.geometry}>
          <MaterialRed />
        </mesh>
      </group>
    </e.group>
  )
}

// useGLTF.preload('/miyajima.gltf')

export default Miyajima
