/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { useFrame } from "@react-three/fiber"

import { MaterialGreenLight, MaterialRed, MaterialWater } from "../materials"

const Miyajima = () => {
  const { nodes } = useGLTF("/planets/miyajima.gltf")

  const ref: null | { current: THREE.Mesh } = useRef()

  useFrame(() => {
    if (ref) {
      const x = ref.current.rotation.x + 0.001
      const y = ref.current.rotation.y + 0.002
      const z = ref.current.rotation.z + 0.003
      ref.current.rotation.set(x, y, z)
    }
  })
  return (
    <group dispose={null} scale={2} position={[-10, 5, -4]} ref={ref}>
      <mesh geometry={nodes.Cube034.geometry}>
        <MaterialWater />
      </mesh>
      <mesh geometry={nodes.Cube004.geometry}>
        <MaterialGreenLight />
      </mesh>
      <mesh geometry={nodes.Cube005.geometry}>
        <MaterialRed />
      </mesh>
    </group>
  )
}

// useGLTF.preload('/miyajima.gltf')

export default Miyajima
